### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by xuyoji** [meelgroup/barbarik#1]
Those code seems to make the for loop end in the first loop each time. Is this a bug or not?
https://github.com/meelgroup/barbarik/blob/f412674cd6055e4173eaf0d6894538da2a89d671/Verifier.py#L430-L433

**Comment by kuldeepmeel** [comment]
No; this is the correct setup. Whenever code terminates; it prints information about the failure of test caess. 
 
Just to make sure something is not funny in your setup; Can you run comparison with the following tool: https://bitbucket.org/kuldeepmeel/unigen/src/master/  and see if the tool also ends the loop in the first time.

**Comment by xuyoji** [comment]
Thanks for your reply. I think I didn't explained my meaning clearly. Orz
I mean in this for loop, it will always return and end the function in the first iteration(we can see it only by those code).  I want to konw why it works?
Thanks.
https://github.com/meelgroup/barbarik/blob/f412674cd6055e4173eaf0d6894538da2a89d671/Verifier.py#L424-L433

**Comment by kuldeepmeel** [comment]
Could you please paste the outputFile for us to help debug and give precise instructions on how to reproduce the behavior you are seeing.

**Comment by xuyoji** [comment]
Emm...
It's not about my outputFile, It's about the code itself. I mean, you see, the for loop above will always return in the fisrt iteration, right?

**Comment by kuldeepmeel** [comment]
Ah yes; You are right. Old code of a different algorithm still lying around; The code is performing the correct behavior; we are refactoring the code right now and will fix the code style. Thank you for highlighting this.

**Comment by kuldeepmeel** [comment]
We have refactored the code. In the process, we found that one of the expressions had delta and epsilon mixed up -- so thanks for raising the issue. 
Please let us know if you are having any trouble using the tool.
